### ISSUE TITLE
Request for publishing

### ISSUE THREAD

**Issue by jschpp** [armentpau/CSVValidator#1]
Will you publish this module on powershell gallery?

**Comment by armentpau** [comment]
That is the eventual goal - I want to get a few things resolved first before pushing to the gallery - but if things go well I should hopefully have that done tonight.  I want to finish some documentation as well as add some options I found would help with a work project.

**Comment by armentpau** [comment]
The code has been uploaded to the gallery

https://www.powershellgallery.com/packages/CSVValidator/1.0.0.0

**Comment by jschpp** [comment]
Thank you 👍
